=== mytrycs/mule/modules/extensions-xml-support/src/main/resources/META-INF/zernova-module.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns="https://schemas.zernova.dev/module"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:zernova="https://schemas.zernova.dev/core"
            targetNamespace="https://schemas.zernova.dev/module"
            attributeFormDefault="unqualified"
            elementFormDefault="qualified">

    <xsd:import namespace="http://www.w3.org/XML/1998/namespace"/>
    <xsd:import namespace="https://schemas.zernova.dev/core"
                schemaLocation="https://schemas.zernova.dev/core/current/zernova.xsd"/>

    <xsd:element name="module" type="moduleConfigType">
        <xsd:annotation>
            <xsd:documentation>
                Root element of a module that contains either properties, operations, or mule global elements as child.
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>

    <xsd:element name="operation" type="operationType">
        <xsd:annotation>
            <xsd:documentation>
                An operation that will be exposed by the module, it behaves like a function as it has a set of input parameters and a single output
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>

    <xsd:complexType name="operationType">
        <xsd:complexContent>
            <xsd:extension base="zernova:abstractExtensionType">
                <xsd:sequence>
                    <xsd:element name="parameters" minOccurs="0" maxOccurs="1">
                        <xsd:annotation>
                            <xsd:documentation>
                                Set of parameters that wil be used to feed a new event, that will be passed through the scope defined by the body
                            </xsd:documentation>
                        </xsd:annotation>
                        <xsd:complexType>
                            <xsd:sequence>
                                <xsd:element ref="parameter" minOccurs="1" maxOccurs="unbounded"/>
                            </xsd:sequence>
                        </xsd:complexType>
                    </xsd:element>
                    <xsd:element name="body">
                        <xsd:annotation>
                            <xsd:documentation>
                                Collection of message processors that can be callable from a scope.
                            </xsd:documentation>
                        </xsd:annotation>
                        <xsd:complexType>
                            <xsd:sequence>
                                <xsd:group ref="zernova:messageProcessorOrMixedContentMessageProcessor" maxOccurs="unbounded"/>
                            </xsd:sequence>
                        </xsd:complexType>
                    </xsd:element>
                    <xsd:element ref="output" minOccurs="0" maxOccurs="1"/>
                    <xsd:element ref="output-attributes" minOccurs="0" maxOccurs="1"/>
                    <xsd:element name="errors" minOccurs="0" maxOccurs="1">
                        <xsd:annotation>
                            <xsd:documentation>
                                Collection of errors that might be thrown by the current operation.
                            </xsd:documentation>
                        </xsd:annotation>
                        <xsd:complexType>
                            <xsd:sequence>
                                <xsd:element ref="error" minOccurs="1" maxOccurs="unbounded"/>
                            </xsd:sequence>
                        </xsd:complexType>
                    </xsd:element>
                </xsd:sequence>
                <xsd:attribute name="name" use="required">
                    <xsd:annotation>
                        <xsd:documentation>
                            Every operation must be named so that it can be called in a mule application.
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:attribute>
                <xsd:attribute name="displayName" type="xsd:string" use="optional">
                    <xsd:annotation>
                        <xsd:documentation>
                            Display name of the operation. It can be any string. When empty, it will default to an auto generated one from the name attribute.
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:attribute>
                <xsd:attribute name="summary" type="xsd:string" use="optional">
                    <xsd:annotation>
                        <xsd:documentation>
                            A very brief overview about this operation.
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:attribute>
                <xsd:attribute name="example" type="xsd:string" use="optional">
                    <xsd:annotation>
                        <xsd:documentation>
                            An example about the content of this operation.
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:attribute>
                <xsd:attribute name="visibility" type="visibilityType" default="PUBLIC">
                    <xsd:annotation>
                        <xsd:documentation>
                        Describes weather the operation can be accessible outside the module or not.
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:attribute>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:element name="error" type="errorType">
        <xsd:annotation>
            <xsd:documentation>
                Defined error for the current operation.
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>

    <xsd:complexType name="errorType">
        <xsd:complexContent>
            <xsd:extension base="zernova:annotatedType">
                <xsd:attribute name="type" type="xsd:string" use="required"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:element name="parameter" type="parameterType">
        <xsd:annotation>
            <xsd:documentation>
                A parameter element defines an input value for the operation in which it is define. Such parameter must be defined with a meaningful name, a type which defines the kind of content the parameter must have and optionally a default value that will be used if the invocation to the operation does not defines a value for the parameter. The parameter can be accessed within the body definition of the operation using an expression such as #[mel: param.paramName]
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>

    <xsd:complexType name="parameterType">
        <xsd:complexContent>
            <xsd:extension base="zernova:annotatedType">
                <xsd:attribute name="name" type="xsd:string" use="required"/>
                <xsd:attribute name="defaultValue" type="xsd:string" use="optional"/>
                <xsd:attribute name="use" type="useType" default="AUTO"/>
                <xsd:attribute name="type" use="required" type="xsd:string"/>
                <xsd:attribute name="password" type="xsd:boolean" default="false"/>
                <xsd:attribute name="role" type="roleParameterType" default="BEHAVIOUR"/>
                <xsd:attribute name="summary" type="xsd:string" use="optional"/>
                <xsd:attribute name="example" type="xsd:string" use="optional"/>
                <xsd:attribute name="displayName" type="xsd:string" use="optional"/>
                <xsd:attribute name="order" type="xsd:int" use="optional"/>
                <xsd:attribute name="tab" type="xsd:string" use="optional"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:element name="output" type="outputType">
        <xsd:annotation>
            <xsd:documentation>
                Defines the output of the operation if exists, void otherwise.
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>

    <xsd:complexType name="outputType">
        <xsd:complexContent>
            <xsd:extension base="zernova:annotatedType">
                <xsd:attribute name="type" type="xsd:string"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:element name="output-attributes" type="outputAttributesType">
        <xsd:annotation>
            <xsd:documentation>
                Defines the attribute's output of the operation if exists, void otherwise.
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>

    <xsd:complexType name="outputAttributesType">
        <xsd:complexContent>
            <xsd:extension base="zernova:annotatedType">
                <xsd:attribute name="type" type="xsd:string"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:element name="property" type="propertyType">
        <xsd:annotation>
            <xsd:documentation>
                A property element defines an input value for the operation in which it is define. Such property must be defined with a meaningful name, a type which defines the kind of content the property must have and optionally a default value that will be used if the invocation to the operation does not defines a value for the property. The property can be accessed within the body definition of the operation using an expression such as #[mel: property.paramName]
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>

    <xsd:complexType name="propertyType">
        <xsd:complexContent>
            <xsd:extension base="zernova:annotatedType">
                <xsd:attribute name="name" type="xsd:string" use="required"/>
                <xsd:attribute name="defaultValue" type="xsd:string" use="optional"/>
                <xsd:attribute name="use" type="useType" default="AUTO"/>
                <xsd:attribute name="type" type="xsd:string" use="required"/>
                <xsd:attribute name="password" type="xsd:boolean" default="false"/>
                <xsd:attribute name="summary" type="xsd:string" use="optional"/>
                <xsd:attribute name="example" type="xsd:string" use="optional"/>
                <xsd:attribute name="displayName" type="xsd:string" use="optional"/>
                <xsd:attribute name="order" type="xsd:int" use="optional"/>
                <xsd:attribute name="tab" type="xsd:string" use="optional"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="moduleConfigType">
        <xsd:annotation>
            <xsd:documentation>
                A module is defined by three types of elements: properties, global elements and operations.
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexContent>
            <xsd:extension base="zernova:abstractExtensionType">
                <xsd:sequence maxOccurs="unbounded" minOccurs="1">
                    <xsd:choice minOccurs="0" maxOccurs="unbounded">
                        <xsd:element ref="property"/>
                        <xsd:element ref="connection"/>
                        <xsd:element ref="operation" />
                        <xsd:group ref="zernova:muleRootElements">
                            <xsd:annotation>
                                <xsd:documentation>
                                    Any global element that can be used in a mule application must be able to put within a module.
                                </xsd:documentation>
                            </xsd:annotation>
                        </xsd:group>
                    </xsd:choice>
                </xsd:sequence>
                <xsd:attribute name="name" use="required">
                    <xsd:annotation>
                        <xsd:documentation>
                            Name of the module that identifies it.
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:attribute>
                <xsd:attribute name="category" type="categoryType" default="COMMUNITY">
                    <xsd:annotation>
                        <xsd:documentation>
                            Expected category of the module.
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:attribute>
                <xsd:attribute name="vendor" type="xsd:string" default="MuleSoft">
                    <xsd:annotation>
                        <xsd:documentation>
                            Expected vendor of the module.
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:attribute>
                <xsd:attribute name="requiredEntitlement" type="xsd:string" default="false">
                    <xsd:annotation>
                        <xsd:documentation>
                            The required entitlement in the customer module license.
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:attribute>
                <xsd:attribute name="allowsEvaluationLicense" type="xsd:boolean" default="true">
                    <xsd:annotation>
                        <xsd:documentation>
                            If the module can be run with an evaluation license.
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:attribute>
                <!-- DSL XML attributes -->
                <xsd:attribute name="namespace" use="optional">
                    <xsd:annotation>
                        <xsd:documentation>
                            Expected namespace of the module to look for when generating the schemas. If left empty it will
                            default to https://schemas.zernova.dev/[prefix], where [prefix] is the attribute prefix attribute value.
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:attribute>
                <xsd:attribute name="prefix" use="optional">
                    <xsd:annotation>
                        <xsd:documentation>
                            Expected prefix of the module to look for when generating the schemas. If left empty it will create a
                            default one based on the extension's name, removing the words "extension", "module" or "connector" at
                            the end if they are present and hyphenizing the resulting name.
                        </xsd:documentation>
                    </xsd:annotation>
                </xsd:attribute>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:simpleType name="categoryType">
        <xsd:annotation>
            <xsd:documentation>
                Set of defined categories for a module.
            </xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="COMMUNITY"/>
            <xsd:enumeration value="SELECT"/>
            <xsd:enumeration value="PREMIUM"/>
            <xsd:enumeration value="CERTIFIED"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="roleParameterType">
        <xsd:annotation>
            <xsd:documentation>
                Set of defined roles for a given parameter.
                BEHAVIOUR will render attributes;
                CONTENT implies support for DataWeave in place;
                PRIMARY works similarly to CONTENT although it also implies it will map to the payload
            </xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="BEHAVIOUR"/>
            <xsd:enumeration value="CONTENT"/>
            <xsd:enumeration value="PRIMARY"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="useType">
        <xsd:annotation>
            <xsd:documentation>
                Set of defined uses for a given property/parameter.
                REQUIRED implies the property/parameter must be present. It can not be REQUIRED if the parameter/property has a defaultValue;
                OPTIONAL implies the property/parameter could be absent.
                AUTO will default at runtime to REQUIRED if defaultValue is absent, otherwise it will be marked as OPTIONAL.
            </xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="REQUIRED"/>
            <xsd:enumeration value="OPTIONAL"/>
            <xsd:enumeration value="AUTO"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="visibilityType">
        <xsd:annotation>
            <xsd:documentation>
            Set of defined visibilities for a given operation.
            PUBLIC will render the operation in the UI and can be consumed from the application.
            PRIVATE implies no visibility of the operation from the UI neither being consumed by the application, but it can be accessed by the internals of the current module through the TNS support
            </xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="PUBLIC"/>
            <xsd:enumeration value="PRIVATE"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:element name="connection" type="connectionType">
        <xsd:annotation>
            <xsd:documentation>
                A connection defines a set of properties that will be tight to the connection provider mechanism rather than the
                configuration (default behaviour).
            </xsd:documentation>
        </xsd:annotation>
    </xsd:element>

    <xsd:complexType name="connectionType">
        <xsd:complexContent>
            <xsd:extension base="zernova:abstractExtensionType">
                <xsd:sequence maxOccurs="unbounded" minOccurs="1">
                    <xsd:choice minOccurs="1" maxOccurs="unbounded">
                        <xsd:element ref="property"/>
                    </xsd:choice>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>
</xsd:schema>

=== mytrycs/mule/modules/extensions-xml-support/src/test/resources/modules/module-capitalized-name.xml
<?xml version="1.0" encoding="UTF-8"?>
<module name="Capitalized with spaces in the name"
        namespace="https://schemas.zernova.dev/capitalized"

        xmlns="https://schemas.zernova.dev/module"
        xmlns:zernova="https://schemas.zernova.dev/core"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="
           https://schemas.zernova.dev/module https://schemas.zernova.dev/module/current/zernova-module.xsd
           https://schemas.zernova.dev/core https://schemas.zernova.dev/core/current/zernova.xsd">

    <property name="a-property" type="string"/>
    <property name="_theUnderscoreProperty" type="string"/>

    <operation name="set-payload-hardcoded-value">
        <body>
            <zernova:set-payload value="hardcoded value"/>
        </body>
        <output type="string"/>
    </operation>

    <operation name="_underscore-set-payload-with-parameter">
        <parameters>
            <parameter name="_theUnderscore" type="string"/>
        </parameters>
        <body>
            <zernova:set-payload value="#[vars['_theUnderscoreProperty'] ++ ', ' ++ vars['_theUnderscore']]"/>
        </body>
        <output type="string"/>
    </operation>

    <operation name="set-payload-with-name-parameter">
        <parameters>
            <parameter name="name" type="string"/>
        </parameters>
        <body>
            <zernova:set-payload value="#[vars.name]"/>
        </body>
        <output type="string"/>
    </operation>
</module>

=== mytrycs/mule/modules/extensions-xml-support/src/test/resources/modules/schema/module-param-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<module name="module-param-types"
        xmlns="https://schemas.zernova.dev/module"
        xmlns:zernova="https://schemas.zernova.dev/core"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="
           https://schemas.zernova.dev/module https://schemas.zernova.dev/module/current/zernova-module.xsd
           https://schemas.zernova.dev/core https://schemas.zernova.dev/core/current/zernova.xsd">

    <operation name="integer-param-operation">
        <parameters>
            <parameter name="integerParam" type="number"/>
        </parameters>
        <body>
            <zernova:set-payload value="some value"/>
        </body>
        <output type="string"/>
    </operation>

    <operation name="boolean-param-operation">
        <parameters>
            <parameter name="booleanParam" type="boolean"/>
        </parameters>
        <body>
            <zernova:set-payload value="some value"/>
        </body>
        <output type="string"/>
    </operation>

    <operation name="date-param-operation">
        <parameters>
            <parameter name="dateParam" type="date"/>
        </parameters>
        <body>
            <zernova:set-payload value="some value"/>
        </body>
        <output type="string"/>
    </operation>

    <operation name="datetime-param-operation">
        <parameters>
            <parameter name="datetimeParam" type="datetime"/>
        </parameters>
        <body>
            <zernova:set-payload value="some value"/>
        </body>
        <output type="string"/>
    </operation>

    <operation name="string-param-operation">
        <parameters>
            <parameter name="stringParam" type="string"/>
        </parameters>
        <body>
            <zernova:set-payload value="some value"/>
        </body>
        <output type="string"/>
    </operation>

    <operation name="time-param-operation">
        <parameters>
            <parameter name="timeParam" type="time"/>
        </parameters>
        <body>
            <zernova:set-payload value="some value"/>
        </body>
        <output type="string"/>
    </operation>
</module>

=== mytrycs/mule/modules/extensions-xml-support/src/test/resources/modules/schema/module-param-default-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<module name="module-param-default-types"
        xmlns="https://schemas.zernova.dev/module"
        xmlns:zernova="https://schemas.zernova.dev/core"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="
           https://schemas.zernova.dev/module https://schemas.zernova.dev/module/current/zernova-module.xsd
           https://schemas.zernova.dev/core https://schemas.zernova.dev/core/current/zernova.xsd">

    <operation name="integer-param-operation">
        <parameters>
            <parameter name="integerParam" type="number" defaultValue="11"/>
        </parameters>
        <body>
            <zernova:set-payload value="some value"/>
        </body>
        <output type="string"/>
    </operation>

    <operation name="boolean-param-operation">
        <parameters>
            <parameter name="booleanParam" type="boolean" defaultValue="false"/>
        </parameters>
        <body>
            <zernova:set-payload value="some value"/>
        </body>
        <output type="string"/>
    </operation>

    <operation name="date-param-operation">
        <parameters>
            <parameter name="dateParam" type="date" defaultValue="1959-09-07T00:00:00"/>
        </parameters>
        <body>
            <zernova:set-payload value="some value"/>
        </body>
        <output type="string"/>
    </operation>

    <operation name="datetime-param-operation">
        <parameters>
            <parameter name="datetimeParam" type="datetime" defaultValue="1959-09-07T00:00:00"/>
        </parameters>
        <body>
            <zernova:set-payload value="some value"/>
        </body>
        <output type="string"/>
    </operation>

    <operation name="string-param-operation">
        <parameters>
            <parameter name="stringParam" type="string" defaultValue="hello world"/>
        </parameters>
        <body>
            <zernova:set-payload value="some value"/>
        </body>
        <output type="string"/>
    </operation>

    <operation name="time-param-operation">
        <parameters>
            <parameter name="timeParam" type="time" defaultValue="1959-09-07T00:00:00"/>
        </parameters>
        <body>
            <zernova:set-payload value="some value"/>
        </body>
        <output type="string"/>
    </operation>

    <operation name="optional-parameter-operation">
        <parameters>
            <parameter name="optionalParameter" type="string" use="OPTIONAL"/>
        </parameters>
        <body>
            <zernova:set-payload value="some value"/>
        </body>
        <output type="string"/>
    </operation>
</module>

=== mytrycs/mule/modules/extensions-xml-support/src/test/resources/modules/module-documentation.xml
<?xml version="1.0" encoding="UTF-8"?>
<module name="module-documentation"
        doc:description="Documentation for the connector"

        xmlns="https://schemas.zernova.dev/module"
        xmlns:zernova="https://schemas.zernova.dev/core"
        xmlns:doc="https://schemas.zernova.dev/documentation"
        xmlns:tns="https://schemas.zernova.dev/module-documentation"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="
           https://schemas.zernova.dev/module https://schemas.zernova.dev/module/current/zernova-module.xsd
           https://schemas.zernova.dev/core https://schemas.zernova.dev/core/current/zernova.xsd
           https://schemas.zernova.dev/module-documentation https://schemas.zernova.dev/module-documentation/current/zernova-module-documentation.xsd">

    <property name="aPropertyWithDoc" type="string" doc:description="Documentation for the property"/>
    <property name="aHiddenPropertyWithDoc" type="string" password="true" doc:description="Documentation for the hidden property"/>
    <property name="aPropertyDisplayModel" type="string" displayName="A pretty name property" summary="a summary tooltip property" example="SOME_PROPERTY_SAMPLE_DATA"/>
    <property name="aPropertyWithPlacement" type="string" order="42" tab="Not General Property"/>

    <operation name="operation-with-doc" doc:description="Documentation for the operation"
               displayName="A pretty name for the operation" summary="a summary tooltip operation" example="SOME_OPERATION_SAMPLE_DATA" >
        <parameters>
            <parameter name="paramWithDoc" type="string" doc:description="Documentation for the parameter" />
            <parameter name="hiddenParamWithDoc" type="string" password="true" doc:description="Documentation for the hidden parameter" />
            <parameter name="paramDisplayModel" type="string" displayName="A pretty name parameter" summary="a summary tooltip parameter" example="SOME_PARAMETER_SAMPLE_DATA"/>
            <parameter name="paramWithPlacement" type="string" order="17" tab="Not General Parameter"/>
        </parameters>
        <body>
            <zernova:set-payload value="hardcoded value"/>
            <tns:private-operation target="testingSyntheticParameter" someParameter="privateParameterValue"/>
        </body>
        <output type="string" doc:description="Documentation for the output"/>
        <output-attributes type="string" doc:description="Documentation for the output attributes"/>
        <errors>
            <error type="CUSTOM_ERROR_HERE"/>
            <error type="ANOTHER_CUSTOM_ERROR_HERE"/>
        </errors>
    </operation>

    <operation name="anotherOperationWithDoc" doc:description="Documentation for the operation"
               displayName="A pretty name for the operation" summary="a summary tooltip operation" example="SOME_OPERATION_SAMPLE_DATA" >
        <parameters>
            <parameter name="paramWithDoc" type="string" doc:description="Documentation for the parameter" />
            <parameter name="hiddenParamWithDoc" type="string" password="true" doc:description="Documentation for the hidden parameter" />
            <parameter name="paramDisplayModel" type="string" displayName="A pretty name parameter" summary="a summary tooltip parameter" example="SOME_PARAMETER_SAMPLE_DATA"/>
            <parameter name="paramWithPlacement" type="string" order="17" tab="Not General Parameter"/>
        </parameters>
        <body>
            <zernova:set-payload value="hardcoded value"/>
            <tns:private-operation target="testingSyntheticParameter" someParameter="privateParameterValue"/>
        </body>
        <output type="string" doc:description="Documentation for the output"/>
        <output-attributes type="string" doc:description="Documentation for the output attributes"/>
        <errors>
            <error type="CUSTOM_ERROR_HERE"/>
            <error type="ANOTHER_CUSTOM_ERROR_HERE"/>
        </errors>
    </operation>

    <operation name="private-operation" visibility="PRIVATE">
        <parameters>
            <parameter name="someParameter" type="string"/>
        </parameters>
        <body>
            <zernova:set-payload value="private operation"/>
        </body>
        <output type="number"/>
    </operation>
</module>
